book_details/urls.py
from django.urls import path
from book_details.views import *

app_name = 'book_details'

urlpatterns = [
    path('book-detail/<int:key>', show_book_detail, name='show_book_detail'),
    path('add-review/<int:key>', add_review, name='add_review'),
    path('get-reviews-json/', get_reviews_json, name='get_reviews_json'),
    path('add-review-ajax/', add_review_ajax, name='add_review_ajax'),
    path('add-review-flutter/', add_review_flutter, name='add_review_flutter'),
    path('show-review-flutter/<int:key>', show_review_flutter, name='show_review_flutter'),

]

bookmark/urls.py
from django.urls import path
from bookmark.views import show_bookmark, delete_bookmark, delete_bookmark_mobile

app_name = 'bookmark'

urlpatterns = [
    path('<str:key>/', show_bookmark, name='show_bookmark'),
    path('delete/<int:key>', delete_bookmark, name="delete_bookmark"),
    path('<str:key>/delete/', delete_bookmark_mobile, name="delete_bookmark_mobile"),
]

pts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('', include('book_details.urls')),
    path('admin/', admin.site.urls),
    path('', include('profiles.urls')),
    path('show-admin/', include('admin_section.urls')),
    path('b/', include('bookmark.urls')),
    path('auth/', include('authentication.urls')),
    path('api/books/', include("book.urls")),
]

bookmark/models.py
from django.db import models
from django.contrib.auth.models import User
from book.models import Book

class Bookmark(models.Model):
    user = models.ForeignKey(
        User, related_name='bookmarked', on_delete=models.CASCADE)
    book = models.ForeignKey(
        Book, related_name='bookmarked', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

bookmark/views.py
from django.shortcuts import render
from book.models import Book
from django.core.paginator import Paginator
from django.http import JsonResponse, HttpResponse
from django.urls import reverse
from bookmark.models import Bookmark
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
import json


@csrf_exempt
def delete_bookmark_mobile(request, key):
    data = json.loads(request.body)
    pkBook = data.get('pk')
    print(pkBook)
    book = get_object_or_404(Book, pk=pkBook)
    if request.method == 'POST':
        user = request.user
        try:
            existing_bookmark = Bookmark.objects.get(user=user, book=book)
            existing_bookmark.delete()
        except Bookmark.DoesNotExist:
            new_bookmark = Bookmark(user=user, book=book)
            new_bookmark.save()

        return JsonResponse({"status": "success"}, status=200)

def show_bookmark(request, key):
    if request.user.username == key:  
        username = key
        user = User.objects.get(username=username)
        book = user.bookmarked.select_related('book')

        p = Paginator(book, 20)
        page = request.GET.get('page')

        books = p.get_page(page)
        context = {
            'books': books,
            'username' : username,
        }
        return render(request, "bookmark.html", context)
    return HttpResponse("cannot access")

def delete_bookmark(request, key):
    book = get_object_or_404(Book, pk=key)
    if request.method == 'POST':
        user = request.user
        try:
            existing_bookmark = Bookmark.objects.get(user=user, book=book)
            existing_bookmark.delete()
            return JsonResponse({'status': 'unbookmarked'})
        except Bookmark.DoesNotExist:
            new_bookmark = Bookmark(user=user, book=book)
            new_bookmark.save()
            return JsonResponse({'status': 'bookmarked'})

bookmark/templates/bookmark.html
{% extends 'base.html' %} {% load static %} {% block content %}
{% block meta %}
    <title>Bookmark</title>
    {% endblock %}
<style>
  .custom-card {
    box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.3);
    margin-right: 20px;
    margin-bottom: 20px;
    background-color: #526d82;
    color: white;
    width: 20vw;
    height: 50vh;
  }

  body {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    color: black;
    font-family: "Poppins", sans-serif;
  }

  .table-container {
    width: 50%;
  }

  table {
    border-collapse: collapse;
    width: 100%;
  }

  th {
    background-color: #000000;
    color: white;
  }

  td {
    border: 1px solid #ddd;
    padding: 8px;
  }

  tr {
    border: 1px solid #ddd;
    padding: 8px;
    text-align: left;
  }

  .btn-custom,
  .bookmark-button {
    background-color: black;
    color: white;
  }

  .bookmark-button {
    position: relative;
  }

  .bookmark-button.bookmarked {
    color: orange;
    background-color: black;
  }

  .btn-custom:hover,
  .bookmark-button:hover {
    background-color: #f0f0f0;
    color: black;
  }
</style>

<h1></h1>
<br />
<br />
<br />

<h1>BOOKMARK</h1>

{% if books %}

<p>{{username}}'s bookmarked books</p>

<div style="display: flex; align-items: center">
  {% if books.has_previous %}
  <a href="?page=1" class="btn btn-custom" style="margin-right: 10px">
    &laquo; First
  </a>
  <a href="?page={{books.previous_page_number}}" class="btn btn-custom">
    Previous
  </a>
  {% endif %}
</div>

<hr />
<h5>Page {{ books.number }} of {{ books.paginator.num_pages }}</h5>
<hr />

<div style="display: flex; align-items: center">
  {% if books.has_next %}
  <a
    href="?page={{books.next_page_number}}"
    class="btn btn-custom"
    style="margin-right: 10px"
  >
    Next
  </a>
  <a href="?page={{books.paginator.num_pages}}" class="btn btn-custom">
    Last &raquo;
  </a>
  {% endif %}
</div>

<br />
<div id="Item_table_container" class="table-container">
  <table>
    <tr>
      <th width="10%">Cover</th>
      <th width="50%">Title</th>
      <th width="10%">Author</th>
      <th width="10%">Rating</th>
      <th width="10%">Language</th>
      <th width="5%">Bookmark</th>
    </tr>
    {% for bookmark in books %}
    <tr>
      <td>
        <img
          src="https://covers.openlibrary.org/b/isbn/{{bookmark.book.isbn}}-M.jpg"
          class="card-img-top"
          alt="{{book.title}}"
        />
      </td>
      <td> 
        <a
          href="{% url 'book_details:show_book_detail' key=bookmark.book.pk %}"
          style="text-decoration: none; color: black"
          ><b
            ><h5 class="card-title" style="font-weight: bold">
              {{bookmark.book.title}}
            </h5></b
          ></a
        >
      </td>
      <td>{{bookmark.book.author}}</td>
      <td style="text-align: center">{{bookmark.book.average_rating}}/10</td>
      <td style="text-align: center">{{bookmark.book.language_code}}</td>
      <td style="text-align: center">
        <form
          class="bookmark_form"
          method="POST"
          action="{% url 'bookmark:delete_bookmark' bookmark.book.pk %}"
        >
          {% csrf_token %}
          <input
            type="hidden"
            name="bookmarked"
            value="{{ bookmark.book.pk }}"
          />
          <button class="btn bookmark-button bookmarked" type="submit">
            <i class="fa fa-bookmark"></i>
          </button>
        </form>
      </td>
    </tr>
    {% endfor %}
  </table>
</div>

<hr />
<br /><br />

<script>
  document.addEventListener("DOMContentLoaded", (event) => {
    document.querySelectorAll(".bookmark_form").forEach((form) => {
      form.addEventListener("submit", function (event) {
        event.preventDefault();
        fetch(this.action, {
          method: this.method,
          body: new FormData(this),
          headers: {
            "X-Requested-With": "XMLHttpRequest", // NEEDED FOR DJANGO TO TREAT THIS AS AJAX
            "X-CSRFToken": this.querySelector("input[name=csrfmiddlewaretoken]")
              .value, // CSRF TOKEN
          },
        })
          .then((response) => response.json())
          .then((data) => {
            if (data.status === "bookmarked") {
              this.querySelector(".bookmark-button").classList.add(
                "bookmarked"
              );
            } else {
              this.querySelector(".bookmark-button").classList.remove(
                "bookmarked"
              );
            }
          });
      });
    });
  });
</script>
{% else %}
<p>Bookmark Anda masih kosong :(</p>

{% endif %} {% endblock content %}