bookmark/urls.py
from django.urls import path
from bookmark.views import show_bookmark, delete_bookmark, delete_bookmark_mobile

app_name = 'bookmark'

urlpatterns = [
    path('<str:key>/', show_bookmark, name='show_bookmark'),
    path('delete/<int:key>', delete_bookmark, name="delete_bookmark"),
    path('<str:key>/delete/', delete_bookmark_mobile, name="delete_bookmark_mobile"),
]

profiles/urls.py
from django.urls import path
from profiles.views import *

app_name = 'profiles'

urlpatterns = [
    path('preference/', preference, name='preference'),
    path('showprofile/', showprofile, name='showprofile'),
    path('pref_json/', pref_json, name='pref_json'),
    path('ret_review/', ret_review, name='ret_review'),
    path('ret_profile/', ret_profile, name='ret_profile'),
    path('change_pref/', change_pref, name='change_pref'),
    path('set_pref/', set_pref, name='set_pref')
]

pts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('', include('book_details.urls')),
    path('admin/', admin.site.urls),
    path('', include('profiles.urls')),
    path('show-admin/', include('admin_section.urls')),
    path('b/', include('bookmark.urls')),
    path('auth/', include('authentication.urls')),
    path('api/books/', include("book.urls")),
]

profiles/models.py
from django.db import models
from book.models import *
from book_details.models import *
# Create your models here.
class Preference(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    author = models.CharField(("author"), max_length=255)

profiles/forms.py
from django import forms
from book.models import Book

class DynamicCheckboxForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(DynamicCheckboxForm, self).__init__(*args, **kwargs)
        queryset = Book.objects.order_by('-text_review_count').values('author').exclude(author__icontains='/').distinct()
        index = 0
        for obj in queryset:
            self.fields[str(index)] = forms.BooleanField(label=str(obj['author']), required=False)
            index += 1
            # if index == 16:
            #     break

profiles/views.py
from django.shortcuts import render, redirect
from book.models import Book
from django.contrib import messages
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.decorators import login_required
from profiles.forms import *
from profiles.models import *
from bookmark.models import *
from django.core import serializers
import random
import json
from admin_section.models import *
from admin_section.models import Review
from django.contrib.auth import get_user
from django.views.decorators.csrf import csrf_exempt

# Create your views here.


@login_required(login_url='/login')
def preference(request):
    author = Book.objects.all().values('author').exclude(
        author__icontains='/').distinct()
    form = DynamicCheckboxForm(request.POST or None)
    start = random.randrange(0, 50)
    first_half_fields = list(form)[start:start+8]
    second_half_fields = list(form)[start+8:start+16]
    context = {
        'author': author,
        'form': form,
        'first_half_fields': first_half_fields,
        'second_half_fields': second_half_fields
    }
    if request.method == "POST":
        counter = 0
        flag = False
        if form.is_valid():
            for field in form.cleaned_data:
                if form.cleaned_data[field] == True:
                    flag = True
                    break
            if flag == True:
                Preference.objects.filter(user=get_user(request)).delete()
            else:
                return redirect('profiles:showprofile')
            for field in form.cleaned_data:
                if form.cleaned_data[field]:
                    # Assuming the field name is the author's name
                    author_name = form.fields[str(field)].label
                    preference, created = Preference.objects.get_or_create(
                        user=get_user(request), author=author_name)
                    if created:
                        counter += 1
                        preference.save()
                    preferences = Preference.objects.filter(
                        user=get_user(request)).values('author')
            return redirect('profiles:showprofile')

    return render(request, "preference.html", context)


@login_required(login_url='/login')
def showprofile(request):
    user_now = get_user(request)
    review = Review.objects.filter(user=user_now)
    preference = Preference.objects.filter(user=user_now)
    for pref in preference:
        print(pref.author)
    context = {'user': user_now, 'review': review, 'pref': preference}
    return render(request, "showprofile.html", context)


@login_required(login_url='/login')
def pref_json(request):
    preferences = Preference.objects.filter(user=get_user(request))
    return HttpResponse(serializers.serialize('json', preferences))

@login_required(login_url='/login')
def ret_profile(request):
    user = get_user(request)
    if (user.is_superuser):
        role = "Admin"
    else:
        if (user.username == "admin"):
            role = 'Admin'
        else:
            role = "User"

    data = {
        'user': user.username,
        'role': role,
    }

    # Return it as JSON
    return JsonResponse(data)

@login_required(login_url='/login')
def ret_review(request):
    title = []
    reviewnya = []
    author = []
    reviews = Review.objects.filter(user=get_user(request))
    for elem in reviews:
        title.append(elem.title)
        reviewnya.append(elem.review)
        author.append(elem.book.author)
    return JsonResponse({'title': title, 'reviewnya': reviewnya, 'author':author})

def change_pref(request):
    author = Book.objects.all().values('author').exclude(
        author__icontains='/').distinct()
    author_list = list(author)  # Convert queryset to list
    random_authors = random.sample(author_list, 8)  # Get 8 random elements
    return JsonResponse({'author':random_authors})

@csrf_exempt
def set_pref(request):
    Preference.objects.filter(user=get_user(request)).delete()
    if request.method == 'POST':
        data = json.loads(request.body)
        for item in data["valid"]:
            new_pref = Preference.objects.create(user=get_user(request), author=item)
            new_pref.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

profiles/templates/preference.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
  <title>Preference</title>
{% endblock %}

{% block content %}
  <style>
    body {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      margin: 0;
    }
    
    .pick {
      padding: 20px;
      display: flex;
      justify-content: center;
      align-items: center;
      flex-direction: column;
      font-family: 'Poppins', sans-serif;
    
      width: 50vw;
      height: 70vh;
      border-radius: 30px;
      box-shadow:  0 8px 12px rgba(0, 0, 0, 0.1);
    }
    
    .form-outline .form-control {
      background-color: #f0f0f0;
    }

    .btn-custom {
    background-color: black;
    color: white;
}

.btn-custom:hover {
    background-color: #f0f0f0;
    color: black;
}
  </style>
  <div class="pick">
    <h1 style="margin-top: 20px;"><b>Preferences</b></h1>
    <h3 style="margin-top: 20px;"><b>Silahkan pilih dari pilihan yang ada!</b></h3>

    <section class="vh-100">
      <div class="container py-5 h-100">
            <form method="post">
              {% csrf_token %}
              <div class="row">
        <div class="col">
            {% for field in first_half_fields %}
            <p>{{ field.label_tag }} {{ field }}</p>
            {% endfor %}
        </div>
        <div class="col">
            {% for field in second_half_fields %}
            <p>{{ field.label_tag }} {{ field }}</p>
            {% endfor %}
    </div>
              <input type="submit" value="Submit" class = "btn btn-light" display="flex" justify-content="text-center">
          </form>
        </div>
      </div>
    </section>
  </div>
{% endblock %}

profiles/templates/showprofile.html
{% extends 'base.html' %} {% load static %} {% block content %} {% block meta %}
<script
      src="https://code.jquery.com/jquery-3.7.1.min.js"
      integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
      crossorigin="anonymous"
    ></script>
<title>Profile</title>
{% endblock %}
<style>
      .custom-card {
      box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.3);
      margin-right: 20px;
      margin-bottom: 20px;
      background-color: white;
      color: black;
      width: 20vw;

      border: 1px solid black;
  }

  body {
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      color: black;
      font-family: 'Poppins', sans-serif;
  }

  .landing-container {
      width: 100vw;
      height: auto;

      display: flex;
      justify-content: space-evenly;
      align-items: flex-start;
      background-color: white;
  }


  .landing-text-container {
      max-width: 50%;
      text-align: justify;

  }


  .landing-img-container {
      max-width: 50%;


  }

  .card-deck {
      display: flex;
      flex-direction: row;
      justify-content: center;
      align-items: center;
      flex-wrap: wrap;
  }

  .custom-card .card-img-top {
      width: 100%;
      height: 50%;
      object-fit: cover;
  }

  .btn-custom {
      background-color: black;
      color: white;
  }

  .btn-custom:hover {
      background-color: #f0f0f0;
      color: black;
  }

  {% comment %} .btn-primary {
      background-color: black;
  }

  .btn-primary:hover {
      background-color: white;

      text-color: black;
  }

  .btn-primary:focus
  {
      font-size: 13px;
      color:orange;
  } {% endcomment %}
</style>
<title>Profile</title>

<div class="landing-container" style="margin-top: 70px">
  <div class="landing-text-container">
    <h1>Profile Information</h1>
    <hr />
    <h3 style="overflow: hidden; text-overflow: ellipsis">User</h3>
    <div class="input-group mb-3">
      <input
        type="text"
        class="form-control"
        placeholder="{{ user }}"
        aria-label="Username"
        aria-describedby="basic-addon1"
        disabled
      />
    </div>

    <br />
    <h3 style="overflow: hidden; text-overflow: ellipsis">Role</h3>
    {% if user.is_superuser %}
    <p>Admin</p>
    {% else %}
    <p>User</p>
    {% endif %}
    <br />

    <h3 style="overflow: hidden; text-overflow: ellipsis">My Preference</h3>
    {% if pref %}
    <table id="preferences"></table>
    <a
      href="{% url 'profiles:preference' %}"
      class="btn btn-light"
      tabindex="-1"
      role="button"
      aria-disabled="true"
      >Ubah Preference</a
    ><br />
    {% else %}
    <p>Anda belum menambahkan Preference :(</p>
    <a
      href="{% url 'profiles:preference' %}"
      class="btn btn-light"
      tabindex="-1"
      role="button"
      aria-disabled="true"
      >Tambah Preference</a
    ><br />

    {% endif %}

    <br />

    <h3 style="overflow: hidden; text-overflow: ellipsis">Last Bookmarked</h3>

    <p>Cek Bookmark Anda disini!</p>
    <a
      href="{% url 'bookmark:show_bookmark' request.user%}"
      class="btn btn-light"
      tabindex="-1"
      role="button"
      aria-disabled="true"
      >BookMark</a
    ><br />

    <br />

    <h3 style="overflow: hidden; text-overflow: ellipsis">Last Reviewed</h3>
    {% if review %}
    <div id="container">
      {% for rev in review %}
      <div class="element">
        "{{rev.review}}"<br />{{rev.book.title}} by {{rev.book.author}}"<br /><br />
      </div>
      {% endfor %}
      <br />
    </div>

    <button id="toggleButton" class="btn btn-light">Show More</button>
    
    <script>
      async function getPref() {
        return fetch("{% url 'profiles:pref_json' %}").then((res) =>
          res.json()
        );
      }
      async function refreshPreference() {
        document.getElementById("preferences").innerHTML = "";
        const products = await getPref();
        let htmlString = ``;
        products.forEach((item) => {
          htmlString += `\n<tr>
                <td>${item.fields.author}</td>
            </tr>`;
        });

        document.getElementById("preferences").innerHTML = htmlString;
      }

      refreshPreference();

      $(document).ready(function () {
        $("#container .element:gt(0)").hide();

        var areElementsShown = false;

        $("#toggleButton").click(function () {
          if (areElementsShown) {
            $("#container .element:gt(0)").slideUp();
            $(this).text("Show More");
            areElementsShown = false;
          } else {
            $("#container .element").slideDown();
            $(this).text("Hide");
            areElementsShown = true;
          }
        });
      });
    </script>
    {% else %}
    <p>Review Anda masih kosong :(</p>
    {% endif %}
  </div>
  <div class="landing-img-container">
    <img
      src="{% static 'img/book.png' %}"
      alt="book"
      style="mix-blend-mode: multiply; max-width: 100%"
    />
  </div>
</div>

<br />

<hr />
<br /><br />
{% endblock content %}