admin_section/urls.py
from django.urls import path
from admin_section.views import *
from book_details.views import show_book_detail
app_name = 'admin_section'

urlpatterns = [
    path('show/', show_admin, name='show_admin'),
    path('book-list-admin/', show_book_list_admin, name='show_book_list_admin'),
    path('user-list/', user_list, name='user_list'),
    path('delete-user/<int:user_id>/', delete_user, name='delete_user'),
    path('get-book/', get_book_json, name='get_book_json'),
    path('create-book-ajax/', add_book_ajax, name='add_book_ajax'),
    path('book-detail/<int:key>', show_book_detail, name='show_book_detail'),
    path('edit-book/<int:id>', edit_book, name='edit_book'),
    path('delete/<int:id>', delete_book, name='delete_book'),
    path('delete-flutter/<int:id>/', delete_book_flutter, name='delete_book_flutter'),
    path('api/users/', get_user, name='user-list'),
    path('create-flutter/', create_book_flutter, name='create_book_flutter'),
    path('edit-flutter/<int:id>', edit_book_flutter, name='edit_book_flutter')
]

bookmark/urls.py
from django.urls import path
from bookmark.views import show_bookmark, delete_bookmark, delete_bookmark_mobile

app_name = 'bookmark'

urlpatterns = [
    path('<str:key>/', show_bookmark, name='show_bookmark'),
    path('delete/<int:key>', delete_bookmark, name="delete_bookmark"),
    path('<str:key>/delete/', delete_bookmark_mobile, name="delete_bookmark_mobile"),
]

main/urls.py
from django.urls import path
from main.views import *
app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('book-list/', show_book_list, name='show_book_list'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('search/', search, name='search'),
    path('sort-books/', sort_books, name='sort_books'),
    path('books-json/', get_book_json, name='get_book_json'),
    path('bookmarks-json/', get_user_bookmark_json, name='get_bookmark_json'),



    path('b/<str:key>', bookmark, name='bookmark'),

]

profiles/urls.py
from django.urls import path
from profiles.views import *

app_name = 'profiles'

urlpatterns = [
    path('preference/', preference, name='preference'),
    path('showprofile/', showprofile, name='showprofile'),
    path('pref_json/', pref_json, name='pref_json'),
    path('ret_review/', ret_review, name='ret_review'),
    path('ret_profile/', ret_profile, name='ret_profile'),
    path('change_pref/', change_pref, name='change_pref'),
    path('set_pref/', set_pref, name='set_pref')
]

pts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('', include('book_details.urls')),
    path('admin/', admin.site.urls),
    path('', include('profiles.urls')),
    path('show-admin/', include('admin_section.urls')),
    path('b/', include('bookmark.urls')),
    path('auth/', include('authentication.urls')),
    path('api/books/', include("book.urls")),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="{% static 'img/book.png' %}" type="image/x-icon" />
    {% block meta %} {% endblock %}
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      rel="stylesheet"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.css"
      rel="stylesheet"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.7.1.min.js"
      integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
      integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
      crossorigin="anonymous"
    ></script>
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.min.css"
      rel="stylesheet"
    />
  </head>

  <body>
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.umd.min.js"
    ></script>
    {% include "navbar.html" %} {% block content %} {% endblock %}
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top bg-transparent">
  <div class="container-fluid px-5">
    {% if user.is_staff %}
    <a class="navbar-brand fs-5" href="{% url 'admin_section:show_admin' %}"><b>UlasBuku</b></a>
    {% else %}
    <a class="navbar-brand fs-5" href="{% url 'main:show_main' %}"><b>UlasBuku</b></a>
    {% endif %}
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="offcanvas"
      data-bs-target="#offcanvasNavbar"
      aria-controls="offcanvasNavbar"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div
      class="sidebar offcanvas offcanvas-start"
      tabindex="-1"
      id="offcanvasNavbar"
      aria-labelledby="offcanvasNavbarLabel"
    >
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">
          <b>UlasBuku</b>
        </h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="offcanvas"
          aria-label="Close"
        ></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-center flex-grow-1 pe-3">
          {% if user.is_staff %}
          <li class="nav-item active mx-3">
            <a class="nav-link" href="{% url 'admin_section:show_admin'%}">Home</a>
          </li>
          {% else %}
          <li class="nav-item active mx-3">
            <a class="nav-link" href="{% url 'main:show_main'%}">Home</a>
          </li>
          {% endif %}
          {% if user.is_staff %}
          <li class="nav-item mx-3">
            <a class="nav-link" href="{% url 'admin_section:show_book_list_admin'%}">Books</a>
          </li>
          {% else %}
          <li class="nav-item mx-3">
            <a class="nav-link" href="{% url 'main:show_book_list'%}">Books</a>
          </li>
          {% endif %}
          <li class="nav-item mx-3">
            <a class="nav-link" href="{% url 'profiles:showprofile' %}"
              >Profile</a
            >
          </li>
          {% if user.is_authenticated %}
            {% if user.is_staff %}
            <li class="nav-item mx-3">
              <a
                class="nav-link"
                href="{% url 'admin_section:user_list'%}"
                >List User</a
              >
            </li>
            {% else %}
            <li class="nav-item mx-3">
              <a
                class="nav-link"
                href="{% url 'bookmark:show_bookmark' request.user%}"
                >Bookmark</a
              >
            </li>
            {% endif %}
          {% endif %}
        </ul>

        <div class="d-flex justify-content-center align-items-center gap-3">
          <a
            class="nav-item"
            href="{% url 'main:logout'%}"
            style="text-decoration: none; color: black"
          >
            Logout <i class="fa fa-sign-in"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>