book_details/urls.py
from django.urls import path
from book_details.views import *

app_name = 'book_details'

urlpatterns = [
    path('book-detail/<int:key>', show_book_detail, name='show_book_detail'),
    path('add-review/<int:key>', add_review, name='add_review'),
    path('get-reviews-json/', get_reviews_json, name='get_reviews_json'),
    path('add-review-ajax/', add_review_ajax, name='add_review_ajax'),
    path('add-review-flutter/', add_review_flutter, name='add_review_flutter'),
    path('show-review-flutter/<int:key>', show_review_flutter, name='show_review_flutter'),

]

main/urls.py
from django.urls import path
from main.views import *
app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('book-list/', show_book_list, name='show_book_list'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('search/', search, name='search'),
    path('sort-books/', sort_books, name='sort_books'),
    path('books-json/', get_book_json, name='get_book_json'),
    path('bookmarks-json/', get_user_bookmark_json, name='get_bookmark_json'),



    path('b/<str:key>', bookmark, name='bookmark'),

]

pts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('', include('book_details.urls')),
    path('admin/', admin.site.urls),
    path('', include('profiles.urls')),
    path('show-admin/', include('admin_section.urls')),
    path('b/', include('bookmark.urls')),
    path('auth/', include('authentication.urls')),
    path('api/books/', include("book.urls")),
]

main/models.py
from django.db import models

# Create your models here.


class Book (models.Model):
    title = models.CharField(("title"), max_length=255)
    author = models.CharField(("author"), max_length=255)
    average_rating = models.FloatField(("average rating"))
    isbn = models.CharField(("isbn"), max_length=150)
    isbn13 = models.CharField(("isbn 13"), max_length=150)
    language_code = models.CharField(("language code"), max_length=10)
    num_pages = models.IntegerField(("number of pages"))
    rating_count = models.BigIntegerField(("rating count"))
    text_review_count = models.BigIntegerField(("text review count"))
    publication_date = models.DateField(("publication date"), auto_now=True)
    publisher = models.CharField(("publisher"), max_length=150)

main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control active', 'type': 'text', 'placeholder': 'Username'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control active', 'placeholder': 'Password'})
    )


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Password again'}))

    class Meta(UserCreationForm.Meta):
        model = User
        # I've tried both of these 'fields' declaration, result is the same
        # fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
        fields = UserCreationForm.Meta.fields

main/views.py
import datetime
from django.shortcuts import render, redirect
from book.models import Book
from django.core.paginator import Paginator
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse, HttpResponse
from django.db.models import Q
from django.core import serializers
import json
from .forms import LoginForm, SignUpForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from bookmark.models import Bookmark
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.db.models import Case, When, Value, IntegerField
from profiles.models import Preference
from django.db.models.query import QuerySet
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user
# Create your views here.


def show_main(request):

    # set pagination 50/page
    last_login = request.COOKIES.get(
        'last_login', 'Tidak ada data login terakhir.')
    context = {
        'last_login': last_login,
    }

    return render(request, "main.html", context)


@login_required(login_url='/login')
def show_book_list(request):

    page = request.GET.get('page')
    sort_param = request.GET.get('sort_by')  # Dapatkan parameter sort

    if sort_param is None:
        sort_param = ""

    if page is None:
        page = 1

    print("sort-param ===" + sort_param)

    if sort_param == 'alphabet-asc':
        books = Book.objects.order_by('title')
    elif sort_param == 'alphabet-desc':
        books = Book.objects.order_by('-title')
    elif sort_param == 'reviews-count':
        books = Book.objects.order_by('-text_review_count')
    elif sort_param == 'preference':
        author = Preference.objects.filter(user=request.user).values('author')
        books = Book.objects.none()
        sisa = Book.objects.none()
        for elem in author:
            books_temp = Book.objects.filter(author=elem['author'])
            for book in books_temp:
                books = books | books_temp
                books_all = Book.objects.all()
                for book2 in books_all:
                    if book.author in book2.author:
                        book2_query = Book.objects.filter(pk=book2.pk)
                        books = books | book2_query
    else:
        books = Book.objects.all()

    p = Paginator(books, 20)
    books = p.get_page(page)

    print('books === ' + str(books))

    b = None
    bookmarks = []
    if request.user.is_authenticated:
        b = request.user.bookmarked.select_related('book')
        for book in b:
            bookmarks.append(book.book)

    context = {
        'books': books,
        'sort_param': sort_param,  # Kirim sort_param kembali ke template
        'bookmarks': bookmarks,
    }

    return render(request, "book_list.html", context)


def get_book_json(request):
    data = Book.objects.all()
    user = request.user
    bookmarks = user.bookmarked.select_related('book')  
    bookmarkedBooks = []
    for bookmark in bookmarks:
        bookmarkedBooks.append(bookmark.book)  

    if data is not None:
        data2 = [{'pk': books.pk, 'models' : 'main.book','fields': {'title': books.title, 'author': books.author, 'average_rating': books.average_rating,
                 'isbn': books.isbn, 'isbn13': books.isbn13, 'language_code': books.language_code, 'num_pages': books.num_pages,
                 'rating_count': books.rating_count, 'text_review_count': books.text_review_count, 'publication_date': books.publication_date,
                 'publisher': books.publisher, 'isBookmarked' : books in bookmarkedBooks }} for books in data]
    else:
        data2 = 0    
    return JsonResponse(data2, safe=False)


def get_user_bookmark_json(request):
    user = request.user
    bookmarks = user.bookmarked.select_related('book')  
    data = []
    for bookmark in bookmarks:
        book_data = serializers.serialize("json", [bookmark.book])
        book_obj = json.loads(book_data)
        data.append(book_obj[0])  # json.loads() mengembalikan list, jadi kita ambil elemen pertama
    if data is not None:
        data2 = [{'pk': books['pk'], 'models': 'main.book', 'fields': {
            'title': books['fields']['title'],
            'author': books['fields']['author'],
            'average_rating': books['fields']['average_rating'],
            'isbn': books['fields']['isbn'],
            'isbn13': books['fields']['isbn13'],
            'language_code': books['fields']['language_code'],
            'num_pages': books['fields']['num_pages'],
            'rating_count': books['fields']['rating_count'],
            'text_review_count': books['fields']['text_review_count'],
            'publication_date': books['fields']['publication_date'],
            'publisher': books['fields']['publisher'],
            'isBookmarked': True
        }} for books in data]
    else:
        data2 = 0            

    return JsonResponse(data2, safe=False)


def bookmark(request, key):
    book = get_object_or_404(Book, pk=key)
    if request.method == 'POST':
        user = request.user
        try:
            existing_bookmark = Bookmark.objects.get(user=user, book=book)
            existing_bookmark.delete()
            return JsonResponse({'status': 'unbookmarked'})
        except Bookmark.DoesNotExist:
            new_bookmark = Bookmark(user=user, book=book)
            new_bookmark.save()
            return JsonResponse({'status': 'bookmarked'})


def register(request):
    form = SignUpForm()
    context = {'form': form}
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'Your account has been successfully created!')
            return redirect('main:login')
        else:
            messages.info(
                request, "Register Failed.")

    return render(request, 'register.html', context)


def login_user(request):
    form = LoginForm()
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            if user.is_staff:
                response = HttpResponseRedirect(
                    reverse('admin_section:show_admin'))
                response.set_cookie('last_login', str(datetime.datetime.now()))
                return response
            else:
                response = HttpResponseRedirect(reverse('main:show_main'))
                response.set_cookie('last_login', str(datetime.datetime.now()))
                return response
        else:
            messages.info(
                request, 'Sorry, incorrect username or password. Please try again.')
    context = {'form': form}
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response


def search(request):
    query = request.GET.get('q')
    user = request.user

    # Misalnya mencari produk berdasarkan nama
    results = Book.objects.filter(title__icontains=query)
    results = Book.objects.filter(
        Q(title__icontains=query) | Q(
            isbn__icontains=query) | Q(author__icontains=query)
    )

    bookmarks = user.bookmarked.select_related('book')
    bookmarkedBooks = []

    for bookmark in bookmarks:
        bookmarkedBooks.append(bookmark.book)

    if results is not None:
        data = [{'pk': books.pk, 'title': books.title, 'author': books.author, 'average_rating': books.average_rating,
                 'isbn': books.isbn, 'isbn13': books.isbn13, 'language_code': books.language_code, 'num_pages': books.num_pages,
                 'rating_count': books.rating_count, 'text_review_count': books.text_review_count, 'publication_date': books.publication_date,
                 'publisher': books.publisher,'isBookmarked' : books in bookmarkedBooks } for books in results]
    else:
        data = 0

    return JsonResponse(data, safe=False)
def sort_books(request):
    sort_by = request.GET.get('sort_by')
    if sort_by == 'alphabet-asc':
        books = Book.objects.order_by('title')
    elif sort_by == 'alphabet-desc':
        books = Book.objects.order_by('-title')
    elif sort_by == 'reviews-count':
        books = Book.objects.order_by('-text_review_count')
    elif sort_by == 'preference':
        author = Preference.objects.filter(user=get_user(request)).values('author')
        books = Book.objects.none()
        for book in books:
            print(book.author)
        for elem in author:
            books_temp = Book.objects.filter(author=elem['author'])
            for book in books_temp:
                print(book.author)
                books = books | books_temp
                books_all = Book.objects.all()
                for book2 in books_all:
                    if book.author in book2.author:
                        book2_query = Book.objects.filter(pk=book2.pk)
                        books = books | book2_query
    else:
        books = Book.objects.all()

    user = request.user
    bookmarks = user.bookmarked.select_related('book')
    bookmarkedBooks = []

    for bookmark in bookmarks:
        bookmarkedBooks.append(bookmark.book)

    book_list = [{'pk': book.pk, 'title': book.title, 'author': book.author, 'average_rating': book.average_rating,
                 'isbn': book.isbn, 'isbn13': book.isbn13, 'language_code': book.language_code, 'num_pages': book.num_pages,
                  'rating_count': book.rating_count, 'text_review_count': book.text_review_count, 'publication_date': book.publication_date,

main/templates/book_list.html
{% extends 'base.html' %} {% load static %} {% block content %} {% block meta %}
<title>Books</title>
{% endblock %}
<script
  src="https://code.jquery.com/jquery-3.7.1.min.js"
  integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
  crossorigin="anonymous"
></script>
<style>
  body {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    color: black;
    font-family: "Poppins", sans-serif;
    padding-top: 100px;
  }

  .card-deck {
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
    flex-wrap: wrap;
    gap: 25px;
  }

  .custom-card {
    display: flex;
    border: 1px solid black;
    box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.3);
    margin-right: 20px;
    margin-bottom: 20px;
    background-color: white;
    color: black;
    width: 300px;
    height: 400px;
    overflow: auto;
  }

  .custom-card .card-img-top {
    width: 100%;
    height: 50%;
    object-fit: cover;
  }

  .bookmark-button {
    position: absolute;
    top: 8px;
    right: 16px;
  }

  .bookmark-button.bookmarked {
    color: orange;
    background-color: black;
  }

  .btn-custom,
  .bookmark-button {
    background-color: black;
    color: white;
  }

  .btn-custom:hover,
  .bookmark-button:hover {
    background-color: #f0f0f0;
    color: black;
  }

  #search-form {
    display: flex;
    flex-direction: row;
  }
  .search-group {
    width: 75vw;
  }
  .form-outline .form-control {
    background-color: #f0f0f0;
  }
</style>

<div id="list-book" class="search-group">
  <form id="search-form" class="form-outline">
    <input
      id="search-focus"
      type="text"
      class="form-control"
      name="q"
      placeholder="Masukkan judul/isbn/author . . ."
    />
    <label class="form-label" for="button">Search</label>
    <button type="submit" class="btn btn-custom">
      <i class="fas fa-search"></i>
    </button>
  </form>
</div>

<br /><br />

<ul
  class="pagination"
  style="
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    justify-content: center;
  "
>
  <li class="page-item">
    <a class="page-link btn-custom" href="#" aria-label="Previous"
      ><span aria-hidden="true">&laquo;</span></a
    >
  </li>
  {% for page in books.paginator.page_range %}
  <li class="page-item">
    <a class="page-link btn-custom" href="?page={{ page }}">{{ page }}</a>
  </li>
  {% endfor %}
  <li class="page-item">
    <a class="page-link btn-custom" href="#" aria-label="Next"
      ><span aria-hidden="true">&raquo;</span></a
    >
  </li>
</ul>

<br />

<div id="sort-by" class="dropdown">
  <button
    class="btn btn-custom dropdown-toggle"
    type="button"
    data-bs-toggle="dropdown"
    aria-expanded="false"
  >
    Sort by
  </button>
  <ul class="dropdown-menu" id="sort-options">
    <li>
      <a class="dropdown-item" href="#" data-sort="alphabet-asc"
        >Alphabet (A-Z)</a
      >
    </li>
    <li>
      <a class="dropdown-item" href="#" data-sort="alphabet-desc"
        >Alphabet (Z-A)</a
      >
    </li>
    <li>
      <a class="dropdown-item" href="#" data-sort="reviews-count"
        >Reviews Count</a
      >
    </li>
    <li>
      <a class="dropdown-item" href="#" data-sort="preference">Preference</a>
    </li>
  </ul>
</div>

<br />

<div id="search-results" class="card-deck">
  {% for book in books %}

  <div class="card card-sm custom-card">
    <img
      src="https://covers.openlibrary.org/b/isbn/{{book.isbn}}-M.jpg"
      class="card-img-top"
      alt="{{book.title}}"
    />
    <div class="card-body">
      <a
        href="{% url 'book_details:show_book_detail' key=book.pk %}"
        style="text-decoration: none; color: black"
        ><b
          ><h5 class="card-title" style="font-weight: bold">
            {{ book.title }}
          </h5></b
        ></a
      >
      <p class="card-text">Author: {{book.author}}</p>
      <p class="card-text">Rating: {{book.average_rating}}/10</p>
      <p class="card-text">Language: {{book.language_code}}</p>
      {% if user.is_authenticated %}
      <form
        class="bookmark_form"
        method="POST"
        action="{% url 'main:bookmark' book.pk %}"
      >
        {% csrf_token %}
        <input type="hidden" name="bookmarked" value="{{ book.pk }}" />
        <button
          class="btn bookmark-button {% if book in bookmarks %}bookmarked{% endif %}"
          type="submit"
        >
          <i class="fa fa-bookmark"></i>
        </button>
      </form>
      {% endif %}
    </div>
  </div>
  {% endfor %}
</div>

<br />

<ul
  class="pagination"
  style="
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    justify-content: center;
  "
>
  <li class="page-item">
    <a class="page-link btn-custom" href="#" aria-label="Previous"
      ><span aria-hidden="true">&laquo;</span></a
    >
  </li>
  {% for page in books.paginator.page_range %}
  <li class="page-item">
    <a class="page-link btn-custom" href="?page={{ page }}">{{ page }}</a>
  </li>
  {% endfor %}
  <li class="page-item">
    <a class="page-link btn-custom" href="#" aria-label="Next"
      ><span aria-hidden="true">&raquo;</span></a
    >
  </li>
</ul>

<script>
  $(document).ready(function () {
    $("#search-results").on("submit", ".bookmark_form_2", function (e) {
      e.preventDefault(); // Prevent default form submission
      var form = $(this);
      var url = form.attr("action");
      var formData = form.serialize();

      $.ajax({
        type: "POST",
        url: url,
        data: formData,
        success: function (data) {
          // Handle success response, maybe update UI accordingly
          if (data.status === "bookmarked") {
            form.find(".bookmark-button").addClass("bookmarked");
          } else if (data.status === "unbookmarked") {
            form.find(".bookmark-button").removeClass("bookmarked");
          }
        },
      });
    });

    $("#sort-options a").click(function (e) {
      e.preventDefault();
      var selectedSort = $(this).data("sort");

      $.ajax({
        type: "GET",
        url: "{% url 'main:sort_books' %}",
        data: { sort_by: selectedSort },

        success: function (data) {
          $("#search-results").html("");
          data.forEach(function (book) {
            var urlDetail =
              "{% url 'book_details:show_book_detail' 0 %}".replace(
                "0",
                book.pk
              );
            var urlBookmark = "{% url 'main:bookmark' 0 %}".replace(
              "0",
              book.pk
            );
            $("#search-results").append(`<div class="card card-sm custom-card">
                <img src="https://covers.openlibrary.org/b/isbn/${book.isbn}-M.jpg" class="card-img-top" style="border-bottom: 2px solid black;" alt="{{ book.title }}" />
                <div class="card-body" style="max-height: 100%; overflow-y: auto;">
                <a
        href= ${urlDetail}
        style="text-decoration: none; color: black"
        ><b
          ><h5 class="card-title" style="font-weight: bold">
            ${book.title}
          </h5></b
        ></a
      >
                <br />
                <p class="card-text">Author: ${book.author}</p>
                <p class="card-text">Rating: ${book.average_rating}/10</p>
                <p class="card-text">Language: ${book.language_code}</p>
                {% if user.is_authenticated %}
      <form
        class="bookmark_form_2"
        method="POST"
        action=${urlBookmark}
      >
        {% csrf_token %}
        <input type="hidden" name="bookmarked" value="${book.pk}" />
        <button
          class="btn bookmark-button {% if book in bookmarks %}bookmarked{% endif %}"
          type="submit"
        >
          <i class="fa fa-bookmark"></i>
        </button>
      </form>
      {% endif %}
                    </div>
                </div>`);
          });

          var currentPage = new URLSearchParams(window.location.search).get(
            "page"
          );

          $(".pagination a").each(function () {
            var href = $(this).attr("href");
            var separator = href.includes("?") ? "&" : "?"; // Check if there are existing parameters
            $(this).attr("href", href + separator + "sort_by=" + selectedSort);
          });
        },
      });
    });

    $("#search-form").submit(function (e) {
      e.preventDefault();
      var query = $("#search-focus").val();

      $.ajax({
        url: "/search/",
        data: { q: query },
        success: function (data) {
          console.log(data);
          $("#search-results").html("");
          if (data.length === 0) {
            $("#search-results").append(
              `<p style="color:black;">Buku tidak ditemukan</p>`
            );
          } else {
            data.forEach(function (book) {
              var urlDetail =
                "{% url 'book_details:show_book_detail' 0 %}".replace(
                  "0",
                  book.pk
                );
              var urlBookmark = "{% url 'main:bookmark' 0 %}".replace(
                "0",
                book.pk
              );
              $(
                "#search-results"
              ).append(`<div class="card card-sm custom-card">
                <img src="https://covers.openlibrary.org/b/isbn/${book.isbn}-M.jpg" class="card-img-top" style="border-bottom: 2px solid black;" alt="{{ book.title }}" />
                <div class="card-body" style="max-height: 100%; overflow-y: auto;">
                <a
        href= ${urlDetail}
        style="text-decoration: none; color: black"
        ><b
          ><h5 class="card-title" style="font-weight: bold">
            ${book.title}
          </h5></b
        ></a
      >
                <br />
                <p class="card-text">Author: ${book.author}</p>
                <p class="card-text">Rating: ${book.average_rating}/10</p>
                <p class="card-text">Language: ${book.language_code}</p>
                {% if user.is_authenticated %}
      <form
        class="bookmark_form_2"
        method="POST"
        action=${urlBookmark}
      >
        {% csrf_token %}
        <input type="hidden" name="bookmarked" value="${book.pk}" />
        <button
          class="btn bookmark-button {% if book in bookmarks %}bookmarked{% endif %}"
          type="submit"
        >
          <i class="fa fa-bookmark"></i>
        </button>
      </form>
      {% endif %}
                    </div>
                </div>`);
            });
          }

          $(".pagination").html("");
          $("#sort-by").html("");
        },
      });
    });
  });

  document.addEventListener("DOMContentLoaded", (event) => {
    document.querySelectorAll(".bookmark_form").forEach((form) => {
      form.addEventListener("submit", function (event) {
        event.preventDefault();
        fetch(this.action, {
          method: this.method,
          body: new FormData(this),
          headers: {
            "X-Requested-With": "XMLHttpRequest", // NEEDED FOR DJANGO TO TREAT THIS AS AJAX
            "X-CSRFToken": this.querySelector("input[name=csrfmiddlewaretoken]")
              .value, // CSRF TOKEN
          },
        })
          .then((response) => response.json())
          .then((data) => {
            if (data.status === "bookmarked") {
              this.querySelector(".bookmark-button").classList.add(
                "bookmarked"
              );
            } else {
              this.querySelector(".bookmark-button").classList.remove(
                "bookmarked"
              );
            }
          });
      });
    });
  });
</script>
{% endblock content %}

main/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block meta %}
    <title>Login</title>
    {% endblock %}
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap"
    />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
      integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
      crossorigin="anonymous"
    ></script>
  </head>

  {% block content %}
  <style>
    body {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      margin: 0;
    }

    .login {
      padding: 20px;
      display: flex;
      justify-content: center;
      align-items: center;
      flex-direction: column;
      font-family: "Poppins", sans-serif;

      width: 50vw;
      height: 70vh;
      border-radius: 30px;
      box-shadow: 0 8px 12px rgba(0, 0, 0, 0.1);
    }

    .form-outline .form-control {
      background-color: #f0f0f0;
    }

    .btn-custom {
      background-color: black;
      color: white;
    }

    .btn-custom:hover {
      background-color: #f0f0f0;
      color: black;
    }
  </style>
  <div class="login">
    <h1 style="margin-top: 20px"><b>Login</b></h1>

    <section class="vh-100">
      <div class="container py-5 h-100">
        <div class="row d-flex align-items-center justify-content-center h-100">
          <div class="col-md-8 col-lg-7 col-xl-6">
            <img
              src="{% static 'img/book.png' %}"
              class="img-fluid"
              alt="Phone image"
            />
          </div>
          <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
            <form class="user" action="" method="POST">
              {% csrf_token %}

              <!-- Email input -->
              <div class="form-outline mb-4">
                <label class="form-label" for="username">Username</label>
                {{ form.username }}
              </div>

              <!-- Password input -->
              <div class="form-outline mb-4">
                <label class="form-label" for="password">Password</label>
                {{ form.password }}
              </div>

              {% if messages %} {% for message in messages %}
              <p>{{ message }}</p>
              {% endfor %} {% endif %}

              <!-- Submit button -->
              <button
                type="submit"
                value="login"
                name="submit"
                class="btn btn-custom btn-lg btn-block"
              >
                Sign in
              </button>

              <div class="divider d-flex align-items-center my-4">
                <p class="text-center fw mx-3 mb-0 text-muted">
                  Belum punya akun?
                  <b
                    ><a style="color: black" href="{% url 'main:register' %}"
                      >Gabung Sekarang</a
                    ></b
                  >
                </p>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
  </div>
  {% endblock %}
</html>

main/templates/main.html
{% extends 'base.html' %} {% load static %} {% block content %} {% block meta %}
<title>Home</title>
{% endblock %}
<style>
  body {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    color: black;
    font-family: "Poppins", sans-serif;
  }

  .landing-container {
    width: 100vw;
    height: 100vh;

    display: flex;
    justify-content: space-evenly;
    align-items: center;
    background-color: white;
  }

  @media (max-width: 1050px) {
    .landing-container {
      flex-direction: column-reverse;
      justify-content: center;
    }
  }

  .landing-text-container {
    max-width: 50%;
    text-align: justify;
  }

  .landing-img-container {
    max-width: 50%;
    height: auto;
  }

  .btn-custom {
    background-color: black;
    color: white;
  }

  .btn-custom:hover {
    background-color: #f0f0f0;
    color: black;
  }
</style>

<div class="landing-container">
  <div class="landing-text-container">
    <h1>Selamat Datang di <b>UlasBuku</b>!</h1>
    <p style="overflow: hidden; text-overflow: ellipsis">
      Tempat di mana kata-kata menghidupkan cerita-cerita dan imajinasi menggenggam keajaiban. 
      Temukan dunia baru di antara halaman-halaman yang penuh dengan hikayat yang menarik untuk mengekspresikan pengalaman membaca Anda.
    </p>
    <a
      class="btn btn-custom"
      href="{% url 'main:show_book_list'%}"
      role="button"
      >Mulai Eksplor</a
    >
  </div>
  <div class="landing-img-container">
    <img
      src="{% static 'img/book.png' %}"
      alt="Designed by pikisuperstar / Freepik"
      style="mix-blend-mode: multiply; max-width: 100%"
    />
  </div>
</div>

{% endblock content %}